### ISSUE TITLE
Command `new` fails with error `assert.AssertionError`

### ISSUE THREAD

**Issue by alepee** [Evaneos/vitaminjs-cli#5]
```
assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: A name parameter is required to create a storage
    at new module.exports (/usr/local/lib/node_modules/vitaminjs-cli/node_modules/yeoman-generator/lib/util/storage.js:24:3)
    at Object.Base._getStorage (/usr/local/lib/node_modules/vitaminjs-cli/node_modules/yeoman-generator/lib/index.js:567:10)
    at Object.module.exports (/usr/local/lib/node_modules/vitaminjs-cli/node_modules/yeoman-generator/lib/index.js:138:22)
    at /usr/local/lib/node_modules/vitaminjs-cli/generators/vitamin/index.js:9:9
    at Environment.instantiate (/usr/local/lib/node_modules/vitaminjs-cli/node_modules/yeoman-environment/lib/environment.js:336:10)
    at Environment.create (/usr/local/lib/node_modules/vitaminjs-cli/node_modules/yeoman-environment/lib/environment.js:313:15)
    at Environment.run (/usr/local/lib/node_modules/vitaminjs-cli/node_modules/yeoman-environment/lib/environment.js:372:24)
    at module.exports (/usr/local/lib/node_modules/vitaminjs-cli/init.js:8:24)
    at Command.program.command.description.option.option.action (/usr/local/lib/node_modules/vitaminjs-cli/index.js:47:4)
    at Command.listener (/usr/local/lib/node_modules/vitaminjs-cli/node_modules/commander/index.js:301:8)`
```

**Comment by alepee** [comment]
seems related to https://github.com/Polymer/polymer-cli/pull/252

**Comment by alepee** [comment]
can be reproduced when invoking `vitaminjs new` within a directory with a `package.json` file which miss a `name` key

**Comment by alepee** [comment]
@Taskim reproduced it within an empty directory (no `package.json`), but we don't know yet why.

**Comment by alepee** [comment]
@LucasPerso @johangirod @christophehurpeau. `yeoman-generator` browse the entire file system tree until it get a `package.json` file. @Taskim had one without a `name` parameter in his `$HOME` directory.
- should we fill an issue on yeoman-generator repository?
- is there an option to ignore `package.json` file in `yeoman-generator` (it should not have to use one since it is supposed to be used in an empty directory with command `new`)

**Comment by johangirod** [comment]
Wow, indeed that's weird. But in a same time, it's understandable (it allows to activate vitaminjs cli from anywhere inside a vitaminjs project). I don't have any idea on what would be the correct thing to do here. Maybe file an issue, and see what they answer ?
